@startuml
skinparam backgroundColor LightYellow
skinparam sequence {
  GroupBackgroundColor SandyBrown
}

/' Icon Definition '/

participant iOS  as ios
participant Edge as edge
participant AC_LOCAL as ac_local
database    DB as db

/' Sequence '/

group Color Code ID Only from iOS or Color Code ID with Image that No Face Can Be Detected
  ios      ->  edge:     Color code ID
  edge     ->  ac_local: Color code ID\n(POST /v1/incoming)
  ac_local ->  db:       Request for retrieving\nsystem status
  db       ->  ac_local: System status
  ac_local ->  ac_local: Logic for determining whether system\nstatus should be changed
  ac_local --> db:       Change system status if need
  ac_local ->  edge:     Response
end

group Image Only from iOS (Face can NOT be Detected)
  ios      ->  edge:     image\n(face can NOT be detected)
  edge     ->  edge:     Do NOT call AC_LOCAL API
end

group Image Only from iOS (Face CAN be Detected)
  ios      ->  edge:     image\n(face CAN be detected)
  edge     ->  ac_local: Temperature Info\n(/v1/sensor_data/thermal_camera/:sensor_id)
  ac_local ->  ac_local: Request for retrieving\nsystem status
  ac_local ->  ac_local: Logic for determining whether system\nstatus should be changed or saving\nreceived info
  ac_local --> db:       Change system status if need
  ac_local --> db:       Save recevied info if need
  ac_local ->  edge:     Response
end

group Color Code ID and Image that Face Can Be Detected
  ios      ->  edge:     Color code ID and image that\nface can be detected
  edge     ->  ac_local: Color code ID\n(POST /v1/incoming)
  ac_local ->  db:       Request for retrieving\nsystem status
  db       ->  ac_local: System status
  ac_local ->  ac_local: Logic for determining whether system\nstatus should be changed
  ac_local --> db:       Change system status if need
  ac_local ->  edge:     Response
  edge     ->  edge:     Face detection
  edge     ->  ac_local: Temperature Info\n(/v1/sensor_data/thermal_camera/:sensor_id)
  ac_local ->  ac_local: Request for retrieving\nsystem status
  ac_local ->  ac_local: Logic for determining whether system\nstatus should be changed or saving\nreceived info
  ac_local --> db:       Change system status if need
  ac_local --> db:       Save recevied info if need
  ac_local ->  edge:     Response
end

@enduml
